[workspace]
members = [
    "crates/common",
    "crates/server",
    "crates/client",
    "crates/client/protocol",
    "crates/launcher",
    "crates/lobby",
    "crates/bundler",
    "crates/backend",
    "crates/backend/api",
]

resolver = "2"

# Build dependencies in release mode for better debug performance.
[profile.dev.package."*"]
opt-level = 3

[patch.crates-io]
slotmap = { git = "https://github.com/caelunshun/slotmap", branch = "feature/try_insert_with_key" }
