[config]
# Disables tasks running for every Cargo workspace member.
default_to_workspace = false

[env]
RIPOSTE_UI_BASE_DIR = "crates/client"

[tasks.build]
command = "cargo"
args = [
    "build",
    "--release",
    "-p", "riposte"
]

[tasks.build.linux]
command = "mold"
args = [
    "-run", "cargo", "build",
    "--release",
    "-p", "riposte"
]

[tasks.build-debug]
command = "cargo"
args = [
   "build",
    "-p", "riposte"
]

[tasks.build-debug.linux]
command = "mold"
args = [
    "-run", "cargo", "build",
    "-p", "riposte"
]

[tasks.run]
dependencies = ["build"]
command = "target/release/riposte"

[tasks.run-debug]
dependencies = ["build-debug"]
command = "target/debug/riposte"

[tasks.profile]
dependencies = ["build"]
command = "perf"
args = [
    "record", "--call-graph=dwarf", "target/release/riposte"
]

[tasks.bundle]
dependencies = ["build"]
command = "cargo"
args = [
    "run",
    "-p", "riposte-bundler"
]

[tasks.generate-ui-code]
script = '''
rm crates/client/src/generated.rs
echo "use crate::ui::flashing_button::FlashingButton; use crate::ui::turn_indicator::TurnIndicatorCircle; use crate::ui::unit_indicator::UnitIndicator;" > crates/client/src/generated.rs
find crates/client/ui -name "*.yml" | xargs -t -I{} duit-codegen {} --append -o crates/client/src/generated.rs
'''
