[config]
# Disables tasks running for every Cargo workspace member.
default_to_workspace = false

[tasks.build]
command = "cargo"
args = [
    "build",
    "--release",
    "-p", "riposte"
]

[tasks.build-debug]
command = "cargo"
args = [
    "build",
    "-p", "riposte"
]

[tasks.run]
dependencies = ["build"]
command = "target/release/riposte"
env = { "RIPOSTE_UI_BASE_DIR" = "crates/client" }

[tasks.run-debug]
dependencies = ["build-debug"]
command = "target/debug/riposte"
env = { "RIPOSTE_UI_BASE_DIR" = "crates/client" }

[tasks.bundle]
dependencies = ["build"]
command = "cargo"
args = [
    "run",
    "-p", "riposte-bundler"
]

[tasks.generate-ui-code]
script = '''
rm client/src/generated.rs
echo "use crate::ui::flashing_button::FlashingButton; use crate::ui::turn_indicator::TurnIndicatorCircle; use crate::ui::unit_indicator::UnitIndicator;" > client/src/generated.rs
find client/ui -name "*.yml" | xargs -t -I{} duit-codegen {} --append -o client/src/generated.rs
'''
