[package]
name = "riposte-bundler"
version = "0.1.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
tar = "0.4"
zstd = { version = "0.9", features = [ "zstdmt" ] }
