[package]
name = "riposte-backend-api"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
bytes = "1"
prost = "0.8"
quinn = "0.7"
tokio-util = { version = "0.6", features = [ "codec" ] }
tonic = "0.5"
uuid = "0.8"

[build-dependencies]
tonic-build = "0.5"
